[phases.setup]
nixPkgs = [
  "php", 
  "phpPackages.composer", 
  "nodejs-18_x",  # This includes npm by default
  "libmysqlclient", 
  "nginx"
]

[phases.install]
cmds = [
  "cp .env.example .env",
  "composer install --no-scripts --ignore-platform-reqs",
  "npm ci"
]

[phases.build]
cmds = [
  "npm run build"
]
[build]
builder = "nixpacks"

[start]
cmd = "php artisan config:cache && php artisan migrate --force && node /assets/scripts/prestart.mjs /assets/nginx.template.conf /nginx.conf && (php-fpm -y /assets/php-fpm.conf & nginx -c /nginx.conf)"
