# railway.toml

# Build configuration
[build]
builder = "nixpacks"
nixpacksPlan.providers = ["php", "node"]
buildCommand = """
    composer install --optimize-autoloader --no-dev &&
    npm install &&
    npm run build &&
    php artisan optimize &&
    php artisan storage:link &&
    php artisan migrate --force
"""

# Deployment configuration for main app service
[deploy]
startCommand = "php artisan serve --host=0.0.0.0 --port=$PORT"
healthcheckPath = "/"
healthcheckTimeout = 60
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 5

# Environment variables
[env]
APP_ENV = "production"
APP_DEBUG = "false"
APP_URL = "${{RAILWAY_PUBLIC_DOMAIN}}"
LOG_CHANNEL = "errorlog"
BROADCAST_CONNECTION = "pusher"
PUSHER_APP_ID = "${{PUSHER_APP_ID}}"
PUSHER_APP_KEY = "${{PUSHER_APP_KEY}}"
PUSHER_APP_SECRET = "${{PUSHER_APP_SECRET}}"
PUSHER_HOST = ""
PUSHER_PORT = "443"
PUSHER_SCHEME = "https"
PUSHER_APP_CLUSTER = "mt1"

# Queue worker service
[[services]]
name = "worker"
startCommand = "php artisan queue:work --tries=3"
internal = true
buildCommand = "${{build.buildCommand}}"
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 5
