# Railway.toml configuration for Laravel application with Pusher

[build]
builder = "nixpacks"
buildCommand = "composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev && php artisan package:discover --ansi && npm ci && npm run build && php artisan config:cache && php artisan route:cache && php artisan view:cache"

[deploy]
startCommand = "php artisan migrate --force && php artisan db:seed --force && php artisan storage:link && php -S 0.0.0.0:$PORT -t public"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 5

[variables]
APP_KEY = "${APP_KEY}"
APP_NAME = "Laravel App"
APP_ENV = "production"
APP_DEBUG = "false"
APP_URL = "${RAILWAY_PUBLIC_DOMAIN}"
LOG_CHANNEL = "stack"
LOG_LEVEL = "error"

# Database Configuration
DB_CONNECTION = "pgsql"
DB_HOST = "${MYSQL_HOST}"
DB_PORT = "${MYSQL_PORT}"
DB_DATABASE = "${MYSQL_DATABASE}"
DB_USERNAME = "${MYSQL_USERNAME}"
DB_PASSWORD = "${MYSQL_PASSWORD}"

# Pusher Configuration
BROADCAST_DRIVER = "pusher"
PUSHER_APP_ID = "${PUSHER_APP_ID}"
PUSHER_APP_KEY = "${PUSHER_APP_KEY}"
PUSHER_APP_SECRET = "${PUSHER_APP_SECRET}"
PUSHER_APP_CLUSTER = "${PUSHER_APP_CLUSTER}"
PUSHER_HOST = ""
PUSHER_PORT = "443"
PUSHER_SCHEME = "https"
PUSHER_APP_ENCRYPTED = "true"

# Queue & Session Configuration
QUEUE_CONNECTION = "database"
SESSION_DRIVER = "database"
SESSION_LIFETIME = "120"

# Cache & File Storage
CACHE_DRIVER = "file"
FILESYSTEM_DISK = "local"

# Mail Configuration
MAIL_MAILER = "log"

[nixpacks]
nodejs-version = "18.x"
php-version = "8.2"

[volumes]
source = "storage"
destination = "/app/storage"
