# Railway.toml configuration for Laravel application with Pusher

[build]
builder = "nixpacks"
buildCommand = "composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev && php artisan package:discover --ansi && npm ci && npm run build && php artisan config:cache && php artisan route:cache && php artisan view:cache"

[deploy]
startCommand = "php artisan migrate --force && php artisan db:seed --force && php artisan storage:link && php -S 0.0.0.0:$PORT -t public"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 5


[nixpacks]
nodejs-version = "18.x"
php-version = "8.2"

[volumes]
source = "storage"
destination = "/app/storage"
