[build]
builder = "nixpacks"
buildCommand = "cp .env.example .env && composer install --no-scripts --ignore-platform-reqs && npm ci && npm run build"

[deploy]
startCommand = "php artisan config:cache && php artisan migrate --force && node /assets/scripts/prestart.mjs /assets/nginx.template.conf /nginx.conf && (php-fpm -y /assets/php-fpm.conf & nginx -c /nginx.conf)"
